env:
  global:
  - secure: nIWYzvmP/2GC8TFYP53WU62kNt3Vn1lqZdFWVjPZLyK90z0Ni6P6IKau6Q8hebxaf9P6S7ihayE5/5lSrWEHzF9Q5NWdG9XeBnagLBbvTktNw/aPjDLPn5LaKSbmfS5Cc1/1v2TGjKyb/PtIzDvZ/a2vlrUrofiHUEUQ6x1lDFln1wtdcfiLuPnztx/CQPMVbuzBPepx1dHgvZtFzierTK1DYPvsJJPDimdXEtK9xB5J2h1/ypf3u1S3/FJhFLU7j12cMGK5ZbGY+svHpbo3PlwFxN79UMWwHSlRcC57S212mwi9FVjSOSAsqBbpUfTBs5tQ3IF0AuHOJ5rNPZGuylPhqrM9LHW4MBPWyxDjPCc8eTEeHQ2gk9LkGn44wTQwXb9JVCx3MwcJmBdmabO8UtR7FZTDOwsPl91nDVeD5Xva1sHgRgocMtCzlm9mGAA0HCdQwfCQkYcBM+IE5uiAx4ZxzjqHdrfiNrXH3HCigKMRarouhz3ebhHopwnlK7NIInEmuXdvzj4iBgdjmUx9uhHu0v4D3RIXzF4RR0F6uKPKr9Ekaiv3suB+37TBYXNlymjmmrWxn2v4odHap0Zhp/NQvb8cSGIWKzJgP/4jB5mYgjyh1xOyAZpyeQr8m9oSP2eXbjLyjNzwZVnPtVO8YEIX9knWrUX/XVr5mMPfRAA=
  - secure: v9P9UrMrxoPgRR/gZlN8zX4xvUb1Wd1fZm5PWNmr9kyl4MJA1Y6nvlN5hlG9LOthQWLJitzDOM14Lm/eWtCBCzansdhszsq4Suc8gPiE4mW3MLL3Oao+MqrI5SVHHSnpcGlqamGzoHFSD1K/fJUcgLjNmHpykdTStYeC7QQvWbSaIis7tr56OmmZHUgXbSKC7VoS0DalCOo9lPzZG+flRp8wn6xhBQDy80PtNxM/DwxD+RduvRGOfPg0Lu+yvroy469u/eRY1VejrCDJ5euac/uRUJkSplVEorA8B26Tnr0RT0Kr7YYFPwLhE8FDudm4er75J7K8kKvNpc/XOxnYXkgpG3KGhG3raX/n+qW49tVeg5Q5TUqEiQJu1vvc6nG/BcbYeg/4qFentLaiJbgfZWSdPJbLzuCbhTTR997ttDqhlm2EvlpLlQjoKEc6/l3PLXLz7nlcsI0lY5TQpFoZJadUTsWYg5tIL1QljGIg8qkQ+h16V2mgu8ZheZFQj32kmbwbnu8Xf6rqDa6ADS8s+6NJM9qtR2+gDIzjqfYFk15Vkv1P1tetJ2rrlsQ/TOD8V+9gHtNOD94KSpBfJ/8zXv8S6nrzjNw6jeb4qMIh4gC7XIk6Q8l3RL7cFQj67vixlRIUImRrYAny6YqUZbI8gRHnv7zVOmW8iGHKamMbqMk=
  - MANAGER_SH="release-manager.sh"
  - MANAGER_URL="https://raw.githubusercontent.com/3mdeb/docker-release-manager/master/release-manager.sh"

sudo: required

services:
  - docker

before_script:
  - wget -O $MANAGER_SH $MANAGER_URL

script:
  - bash $MANAGER_SH build

after_script:
  - docker images

deploy:
  skip_cleanup: true
  provider: script
  script: bash $MANAGER_SH push
  on:
    branch: master
